/**
 * HOME PAGE - STATIC SITE GENERATION (SSG)
 *
 * This is the main landing page demonstrating:
 * 1. File-based routing (app/page.tsx maps to /)
 * 2. Static Site Generation (SSG) for optimal performance
 * 3. Component composition and layout
 *
 * In App Router, this page is statically generated by default
 * unless it uses dynamic functions or data fetching.
 */

import Link from "next/link"
import Image from "next/image"
import { getFeaturedProducts } from "@/lib/data"
import { ArrowRight, Star, Truck, Shield, Headphones } from "lucide-react"

export default function HomePage() {
  // Get featured products (this would typically come from a database)
  const featuredProducts = getFeaturedProducts()

  return (
    <div className="space-y-16">
      {/* Hero Section */}
      <section className="text-center py-16 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-lg">
        <div className="max-w-4xl mx-auto px-4">
          <h1 className="text-5xl font-bold mb-6">Next.js Routing Demo Store</h1>
          <p className="text-xl mb-8 opacity-90">
            Explore our comprehensive demonstration of Next.js routing concepts through a fully functional e-commerce
            experience.
          </p>
          <Link
            href="/products"
            className="inline-flex items-center bg-white text-blue-600 px-8 py-3 rounded-lg font-semibold hover:bg-gray-100 transition-colors"
          >
            Shop Now
            <ArrowRight className="ml-2" size={20} />
          </Link>
        </div>
      </section>

      {/* Features Section */}
      <section>
        <h2 className="text-3xl font-bold text-center mb-12">Why Choose Us?</h2>
        <div className="grid md:grid-cols-3 gap-8">
          <div className="text-center p-6 bg-white rounded-lg shadow-md">
            <Truck className="mx-auto mb-4 text-blue-600" size={48} />
            <h3 className="text-xl font-semibold mb-2">Free Shipping</h3>
            <p className="text-gray-600">Free shipping on all orders over $50</p>
          </div>
          <div className="text-center p-6 bg-white rounded-lg shadow-md">
            <Shield className="mx-auto mb-4 text-green-600" size={48} />
            <h3 className="text-xl font-semibold mb-2">Secure Payment</h3>
            <p className="text-gray-600">Your payment information is always safe</p>
          </div>
          <div className="text-center p-6 bg-white rounded-lg shadow-md">
            <Headphones className="mx-auto mb-4 text-purple-600" size={48} />
            <h3 className="text-xl font-semibold mb-2">24/7 Support</h3>
            <p className="text-gray-600">Get help whenever you need it</p>
          </div>
        </div>
      </section>

      {/* Featured Products Section */}
      <section>
        <div className="flex justify-between items-center mb-8">
          <h2 className="text-3xl font-bold">Featured Products</h2>
          <Link href="/products" className="text-blue-600 hover:text-blue-800 font-semibold flex items-center">
            View All
            <ArrowRight className="ml-1" size={16} />
          </Link>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {featuredProducts.map((product) => (
            <div
              key={product.id}
              className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow"
            >
              <Link href={`/products/${product.id}`}>
                <Image
                  src={product.image || "/placeholder.svg"}
                  alt={product.name}
                  width={300}
                  height={300}
                  className="w-full h-48 object-cover"
                  suppressHydrationWarning={true}
                />
                <div className="p-4">
                  <h3 className="font-semibold text-lg mb-2">{product.name}</h3>
                  <p className="text-gray-600 text-sm mb-2 line-clamp-2">{product.description}</p>
                  <div className="flex justify-between items-center">
                    <span className="text-2xl font-bold text-blue-600">${product.price}</span>
                    <div className="flex items-center">
                      <Star className="text-yellow-400 fill-current" size={16} />
                      <span className="text-sm text-gray-600 ml-1">4.5</span>
                    </div>
                  </div>
                </div>
              </Link>
            </div>
          ))}
        </div>
      </section>

      {/* Routing Concepts Demo Section */}
      <section className="bg-white rounded-lg p-8 shadow-md">
        <h2 className="text-3xl font-bold mb-6">Routing Concepts Demonstrated</h2>
        <div className="grid md:grid-cols-2 gap-6">
          <div>
            <h3 className="text-xl font-semibold mb-3">Static Routes</h3>
            <ul className="space-y-2 text-gray-600">
              <li>
                •{" "}
                <Link href="/" className="text-blue-600 hover:underline">
                  Home Page
                </Link>{" "}
                - Static generation
              </li>
              <li>
                •{" "}
                <Link href="/about" className="text-blue-600 hover:underline">
                  About Page
                </Link>{" "}
                - File-based routing
              </li>
              <li>
                •{" "}
                <Link href="/contact" className="text-blue-600 hover:underline">
                  Contact Page
                </Link>{" "}
                - Static content
              </li>
            </ul>
          </div>
          <div>
            <h3 className="text-xl font-semibold mb-3">Dynamic Routes</h3>
            <ul className="space-y-2 text-gray-600">
              <li>
                •{" "}
                <Link href="/products/1" className="text-blue-600 hover:underline">
                  Product Details
                </Link>{" "}
                - Dynamic [id] route
              </li>
              <li>
                •{" "}
                <Link href="/products/category/electronics" className="text-blue-600 hover:underline">
                  Category Pages
                </Link>{" "}
                - Catch-all routes
              </li>
              <li>
                •{" "}
                <Link href="/api/products" className="text-blue-600 hover:underline">
                  API Routes
                </Link>{" "}
                - Server endpoints
              </li>
            </ul>
          </div>
        </div>
      </section>
    </div>
  )
}
